/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.codeup.academico.ui;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

import com.codeup.academico.domain.Grade;
import com.codeup.academico.domain.Student;
import com.codeup.academico.service.Calculate;
import com.codeup.academico.service.RegisterStudent;
import com.codeup.academico.util.ValidationUtils;
/**
 *
 * @author tonys-dev
 */
public class RegisterStudentFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterStudentFrame.class.getName());

    /**
     * Creates new form JframApp
     */
    public RegisterStudentFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        popupMenu1 = new java.awt.PopupMenu();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        statisticsButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtGrade1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGrade2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGrade3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        lblAverage = new javax.swing.JLabel();
        lblMaxGrade = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        txtAge = new javax.swing.JSpinner();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        calculateButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentsTable = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        lblStudentsAverage = new javax.swing.JLabel();
        lblStudentsMaxGrade = new javax.swing.JLabel();
        lblStudentsResult = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        jButton3.setText("Calculate!");

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 180, 40));

        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        statisticsButton.setBackground(new java.awt.Color(102, 153, 255));
        statisticsButton.setForeground(new java.awt.Color(0, 0, 0));
        statisticsButton.setText("Statistics");
        statisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(statisticsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 600, 110, 40));

        jLabel2.setText("Age");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 70, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 57, 1010, -1));

        txtGrade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrade1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtGrade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 100, 30));

        jLabel3.setText("Grade 1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        txtGrade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrade2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtGrade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 100, 30));

        jLabel4.setText("Grade 2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        txtGrade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrade3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtGrade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 100, 30));

        jLabel5.setText("Grade 3");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        clearButton.setBackground(new java.awt.Color(255, 51, 51));
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 90, 40));

        exitButton.setBackground(new java.awt.Color(255, 51, 51));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 90, 40));
        getContentPane().add(lblAverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 220, 50));
        getContentPane().add(lblMaxGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 220, 50));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel9.setText("Welcome!");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, 50));

        lblResult.setFont(new java.awt.Font("Adwaita Mono", 1, 24)); // NOI18N
        getContentPane().add(lblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 220, 50));
        getContentPane().add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 100, 40));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 409, -1, -1));

        calculateButton.setBackground(new java.awt.Color(102, 255, 102));
        calculateButton.setForeground(new java.awt.Color(0, 0, 0));
        calculateButton.setText("Calculate!");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(calculateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 110, 40));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1010, 10));

        studentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Grade 1", "Grade 2", "Grade 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentsTable);
        if (studentsTable.getColumnModel().getColumnCount() > 0) {
            studentsTable.getColumnModel().getColumn(1).setResizable(false);
            studentsTable.getColumnModel().getColumn(2).setResizable(false);
            studentsTable.getColumnModel().getColumn(3).setResizable(false);
            studentsTable.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        saveButton.setBackground(new java.awt.Color(102, 255, 102));
        saveButton.setForeground(new java.awt.Color(0, 0, 0));
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 110, 40));
        getContentPane().add(lblStudentsAverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 220, 50));
        getContentPane().add(lblStudentsMaxGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 220, 50));

        lblStudentsResult.setFont(new java.awt.Font("Adwaita Mono", 1, 12)); // NOI18N
        getContentPane().add(lblStudentsResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 220, 50));
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 640, 10, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtGrade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrade1ActionPerformed

    private void txtGrade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrade2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrade2ActionPerformed

    private void txtGrade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrade3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrade3ActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        dispose(); // or System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtAge.setValue(0);
        txtGrade1.setText("");
        txtGrade2.setText("");
        txtGrade3.setText("");
        lblAverage.setText("");
        lblMaxGrade.setText("");
        lblResult.setText("");
        lblStudentsAverage.setText("");
        lblStudentsMaxGrade.setText("");
        lblStudentsResult.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void statisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsButtonActionPerformed
        // TODO add your handling code here:
        List<Student> students = RegisterStudent.listStudents();

        lblStudentsAverage.setText("Students Average: " + RegisterStudent.calculateAverage(students));
        lblStudentsMaxGrade.setText("Best Student(s): " + RegisterStudent.getBestStudents(students));
        lblStudentsResult.setText("Approved: " + RegisterStudent.countApproved(students) + " Failed: " + RegisterStudent.countFailed(students));
    }//GEN-LAST:event_statisticsButtonActionPerformed
    
    private void updateStudentsList() {
        var model = (javax.swing.table.DefaultTableModel) studentsTable.getModel();
        model.setRowCount(0); // Cleans the table
        for (var student : RegisterStudent.listStudents()) {
            model.addRow(new Object[]{
                student.getName(),
                student.getAge(),
                student.getGrades().get(0).getValue(),
                student.getGrades().get(1).getValue(),
                student.getGrades().get(2).getValue()
            });
        }
    }
    private class getData {

        private String name(){
            String name = txtName.getText();
            validateInput("name", name);
            return name;
        }

        private int age(){
            Object objAge = txtAge.getValue();
            validateInput("age", objAge);
            return Integer.parseInt(objAge.toString());
        }

        private Object[] strGrades(){
            Object strGrades = new Object[]{txtGrade1.getText(), txtGrade2.getText(), txtGrade3.getText()};
            validateInput("grades", strGrades);
            return (Object[]) strGrades;
        }

        private void validateInput(String type, Object... params) {
            switch (type) {
                case "name" -> ValidationUtils.validateName((String) params[0]);
                case "age" -> ValidationUtils.validateAge(params[0]);
                case "grades" -> ValidationUtils.validateStrGrades((Object[]) params[0]);
            }
        }
        
        private List<Grade> grades() {
            Object[] strGrades = strGrades();
            List<Grade> grades = new ArrayList<>();
            for (Object strGrade : strGrades) {
                grades.add(new Grade(Double.parseDouble(strGrade.toString())));
            }
            return grades;
        }

        private Object[] getEverything() {
            return new Object[]{name(), age(), grades()};
        }

    }
    
    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        // TODO add your handling code here:
        try {
            getData getData = new getData();
            List<Grade> grades = getData.grades();

            lblAverage.setText("Average: " + Calculate.Average(grades));
            lblMaxGrade.setText("Highest grade: " + Calculate.HighestGrade(grades));
            lblResult.setText(Calculate.Approved(grades)? "Approved" : "Failed");

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "IllegalArgument", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        try {
            getData getData = new getData();
            Object[] data = getData.getEverything();
            
            String name = (String) data[0];
            int age = (int) data[1];
            List<Grade> grades = (List<Grade>) data[2];
            
            Student student = new Student(name, age, grades);

            RegisterStudent.addStudent(student);
            updateStudentsList();
            JOptionPane.showMessageDialog(this, "Info: " + "Student saved correctly", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "IllegalArgument", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterStudentFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton exitButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAverage;
    private javax.swing.JLabel lblMaxGrade;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblStudentsAverage;
    private javax.swing.JLabel lblStudentsMaxGrade;
    private javax.swing.JLabel lblStudentsResult;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton statisticsButton;
    private javax.swing.JTable studentsTable;
    private javax.swing.JSpinner txtAge;
    private javax.swing.JTextField txtGrade1;
    private javax.swing.JTextField txtGrade2;
    private javax.swing.JTextField txtGrade3;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
